#!/usr/bin/env python3
"""Skill Management Script Generators

Generates skill manager, explorer, discovery workflow, and list scripts.
"""


def get_manage_skills_script() -> str:
    """Generate skill manager script for adding/removing skills (manage_skills.py)."""
    lines = [
        "#!/usr/bin/env python3",
        '"""Skill Manager - Install and remove Agent Skills."""',
        "import argparse",
        "import os",
        "import shutil",
        "import sys",
        "import urllib.request",
        "from pathlib import Path",
        "",
        "# Github raw content URL pattern",
        'GITHUB_RAW_BASE = "https://raw.githubusercontent.com/{owner}/{repo}/{branch}/{path}"',
        "",
        "def fetch_skill(source: str):",
        '    """Fetch a skill from a URL or GitHub shorthand."""',
        '    print(f"📥 Fetching skill from: {source}")',
        "    ",
        "    # Parse source",
        '    if source.startswith("http"):',
        "        url = source",
        '        filename = source.split("/")[-1]',
        '    elif len(source.split("/")) >= 3:',
        "        # shorthand: owner/repo/path/to/skill.md",
        '        parts = source.split("/")',
        "        owner = parts[0]",
        "        repo = parts[1]",
        '        path = "/".join(parts[2:])',
        '        branch = "main" # Default to main',
        "        ",
        "        # Determine filename",
        "        filename = parts[-1]",
        "        ",
        "        url = GITHUB_RAW_BASE.format(",
        "            owner=owner,",
        "            repo=repo,",
        "            branch=branch,",
        "            path=path",
        "        )",
        "    else:",
        "        print(\"❌ Invalid source format. Use 'owner/repo/path/to/skill.md' or full URL.\")",
        "        sys.exit(1)",
        "        ",
        '    if not filename.endswith(".md"):',
        '        filename += ".md"',
        "",
        "    # Define target path",
        '    target_dir = Path(".agent/skills")',
        "    # If workflow, go to workflows",
        "    title_lower = filename.lower()",
        '    if "workflow" in title_lower or "guide" in title_lower:',
        '         target_dir = Path(".agent/workflows")',
        "    ",
        "    target_dir.mkdir(parents=True, exist_ok=True)",
        "    target_file = target_dir / filename",
        "    ",
        "    try:",
        "        with urllib.request.urlopen(url) as response:",
        "            content = response.read().decode('utf-8')",
        "            ",
        '        with open(target_file, "w") as f:',
        "            f.write(content)",
        "            ",
        '        print(f"✅ Installed: {target_file}")',
        "        ",
        "    except Exception as e:",
        '        print(f"❌ Failed to fetch skill: {e}")',
        "        sys.exit(1)",
        "",
        "def remove_skill(name: str):",
        '    """Remove a local skill."""',
        "    # check skills and workflows",
        "    paths = [",
        '        Path(".agent/skills") / name,',
        '        Path(".agent/skills") / (name + ".md"),',
        '        Path(".agent/workflows") / name,',
        '        Path(".agent/workflows") / (name + ".md")',
        "    ]",
        "    ",
        "    found = False",
        "    for p in paths:",
        "        if p.exists():",
        "            p.unlink()",
        '            print(f"🗑️  Removed: {p}")',
        "            found = True",
        "            ",
        "    if not found:",
        "        print(f\"⚠️  Skill '{name}' not found.\")",
        "",
        "def main():",
        '    parser = argparse.ArgumentParser(description="Skill Manager")',
        '    subparsers = parser.add_subparsers(dest="command", required=True)',
        "    ",
        '    fetch_parser = subparsers.add_parser("fetch", help="Install a skill")',
        '    fetch_parser.add_argument("source", help="GitHub shorthand (owner/repo/path) or URL")',
        "    ",
        '    remove_parser = subparsers.add_parser("remove", help="Remove a skill")',
        '    remove_parser.add_argument("name", help="Name of the skill to remove")',
        "    ",
        "    args = parser.parse_args()",
        "    ",
        '    if args.command == "fetch":',
        "        fetch_skill(args.source)",
        '    elif args.command == "remove":',
        "        remove_skill(args.name)",
        "",
        'if __name__ == "__main__":',
        "    main()",
    ]
    return "\n".join(lines)


def get_explore_skills_script() -> str:
    """Generate skill explorer script for discovering skills from GitHub (explore_skills.py)."""
    lines = [
        "#!/usr/bin/env python3",
        '"""Skill Explorer - Discover and install capabilities from community repositories."""',
        "import argparse",
        "import os",
        "import re",
        "import sys",
        "import urllib.request",
        "import urllib.error",
        "from pathlib import Path",
        "",
        "# Curated sources with known skill paths",
        "CURATED_SOURCES = {",
        '    "anthropics/skills": ["bash.md", "github.md", "editor.md", "sql.md"],',
        '    "google-gemini/gemini-cli": ["examples/skills/"],',
        '    "huggingface/skills": ["skills/"],',
        "}",
        "",
        'GITHUB_RAW = "https://raw.githubusercontent.com/{repo}/main/{path}"',
        "",
        "def extract_title(content: str) -> str:",
        '    """Extract title from markdown (first # heading)."""',
        '    for line in content.split("\\n")[:20]:',
        '        if line.startswith("# "):',
        "            return line[2:].strip()",
        '    return "Untitled Skill"',
        "",
        "def extract_description(content: str) -> str:",
        '    """Extract first paragraph after title."""',
        '    lines = content.split("\\n")',
        "    desc_lines = []",
        "    found_title = False",
        "    ",
        "    for line in lines[:30]:",
        '        if line.startswith("# "):',
        "            found_title = True",
        "            continue",
        '        if found_title and line.strip() and not line.startswith("#"):',
        '            if line.startswith("```"):',
        "                break",
        "            desc_lines.append(line.strip())",
        "            if len(desc_lines) >= 3:",
        "                break",
        "    ",
        '    return " ".join(desc_lines)[:150] + "..." if desc_lines else "No description available"',
        "",
        "def fetch_skill_content(repo: str, path: str) -> str:",
        '    """Fetch raw skill content from GitHub."""',
        "    url = GITHUB_RAW.format(repo=repo, path=path)",
        "    try:",
        "        with urllib.request.urlopen(url, timeout=5) as response:",
        '            return response.read().decode("utf-8")',
        "    except Exception:",
        "        return None",
        "",
        "def discover_skills(query: str):",
        '    """Discover skills from curated sources."""',
        "    skills = []",
        "    query_lower = query.lower()",
        "    ",
        "    # Match repositories",
        "    for repo, paths in CURATED_SOURCES.items():",
        '        if query_lower == "all" or query_lower in repo.lower():',
        "            for path in paths:",
        "                content = fetch_skill_content(repo, path)",
        "                if content:",
        "                    skills.append({",
        '                        "repo": repo,',
        '                        "path": path,',
        '                        "content": content,',
        '                        "title": extract_title(content),',
        '                        "description": extract_description(content),',
        '                        "source": f"{repo}/{path}"',
        "                    })",
        "    ",
        "    return skills",
        "",
        "def preview_skill(content: str, max_lines: int = 20):",
        '    """Display skill preview."""',
        '    lines = content.split("\\n")',
        "    preview_lines = lines[:max_lines]",
        "    total_lines = len(lines)",
        "    ",
        '    print("\\n" + "━" * 60)',
        '    print("\\n".join(preview_lines))',
        '    print("━" * 60)',
        '    print(f"(showing first {max_lines} lines, {total_lines} total)\\n")',
        "",
        "def install_skill(skill: dict):",
        '    """Install a skill to .agent/ directory."""',
        "    # Determine target directory",
        '    filename = skill["path"].split("/")[-1]',
        '    if not filename.endswith(".md"):',
        '        filename += ".md"',
        "        ",
        '    title_lower = skill["title"].lower()',
        '    if "workflow" in title_lower or "guide" in title_lower:',
        '        target_dir = Path(".agent/workflows")',
        "    else:",
        '        target_dir = Path(".agent/skills")',
        "    ",
        "    target_dir.mkdir(parents=True, exist_ok=True)",
        "    target_file = target_dir / filename",
        "    ",
        "    # Check if exists",
        "    if target_file.exists():",
        '        overwrite = input(f"⚠️  {filename} already exists. Overwrite? [y/N]: ").strip().lower()',
        '        if overwrite != "y":',
        '            print("❌ Installation cancelled")',
        "            return False",
        "    ",
        "    # Write file",
        "    try:",
        '        with open(target_file, "w") as f:',
        '            f.write(skill["content"])',
        '        print(f"✅ Installed to: {target_file}")',
        "        return True",
        "    except Exception as e:",
        '        print(f"❌ Failed to install: {e}")',
        "        return False",
        "",
        "def interactive_selection(skills: list):",
        '    """Interactive menu for skill selection and installation."""',
        "    if not skills:",
        '        print("\\n❌ No skills found matching your query.")',
        '        print("\\n💡 Try: make discover q="all" to see all curated skills")',
        "        return",
        "    ",
        '    print(f"\\nFound {len(skills)} skill(s):\\n")',
        "    ",
        "    # Display menu",
        "    for i, skill in enumerate(skills, 1):",
        '        print("━" * 60)',
        "        print(f\"[{i}] {skill['title']}\")",
        "        print(f\"    {skill['description']}\")",
        "        print(f\"    📦 Source: {skill['source']}\")",
        '        print(f"    ⭐ Verified Repository")',
        '    print("━" * 60)',
        "    ",
        "    installed_count = 0",
        "    ",
        "    # Installation loop",
        "    while True:",
        '        print(f"\\nInstall a skill? [1-{len(skills)}, n to skip]: ", end="")',
        "        choice = input().strip().lower()",
        "        ",
        '        if choice == "n" or choice == "":',
        "            break",
        "        ",
        "        try:",
        "            idx = int(choice) - 1",
        "            if 0 <= idx < len(skills):",
        "                skill = skills[idx]",
        "                print(f\"\\n📄 Previewing: {skill['title']}\")",
        '                preview_skill(skill["content"])',
        "                ",
        '                confirm = input("✅ Install this skill? [y/N]: ").strip().lower()',
        '                if confirm == "y":',
        "                    if install_skill(skill):",
        "                        installed_count += 1",
        "                else:",
        '                    print("⏭️  Skipped")',
        "            else:",
        '                print(f"❌ Invalid choice. Enter 1-{len(skills)} or n")',
        "        except ValueError:",
        '            print(f"❌ Invalid input. Enter a number 1-{len(skills)} or n")',
        "    ",
        "    if installed_count > 0:",
        '        print(f"\\n🎉 Done! Installed {installed_count} skill(s).")',
        "    else:",
        '        print("\\n👋 No skills installed.")',
        "",
        "def search_github(query: str):",
        '    """Search and display skills interactively."""',
        "    print(f\"🔍 Searching for skills related to '{query}'...\")",
        "    ",
        "    skills = discover_skills(query)",
        "    interactive_selection(skills)",
        "",
        "def main():",
        "    parser = argparse.ArgumentParser(",
        '        description="Skill Explorer - Discover and install AI agent capabilities"',
        "    )",
        "    parser.add_argument(",
        '        "command",',
        '        choices=["search"],',
        '        help="Command to run"',
        "    )",
        "    parser.add_argument(",
        '        "query",',
        "        help=\"Search term (try 'all', 'bash', 'sql', etc.)\"",
        "    )",
        "    ",
        "    args = parser.parse_args()",
        "    ",
        '    if args.command == "search":',
        "        search_github(args.query)",
        "",
        'if __name__ == "__main__":',
        "    main()",
    ]
    return "\n".join(lines)


def get_skill_discovery_workflow() -> str:
    """Generate the Skill Discovery workflow."""
    lines = [
        "# Workflow: Skill Discovery Protocol",
        "",
        "**Goal**: Identify, Evaluate, and Install new capabilities from external sources.",
        "",
        "## 1. Search",
        "Run the explorer to find relevant repositories:",
        "```bash",
        'make discover q="topic"  # e.g., "python", "docker", "web"',
        "```",
        "",
        "## 2. Evaluate",
        "Before installing, evaluate the source:",
        "- Check the repository URL.",
        "- Look for `.md` files in `skills/` or `tools/` directories.",
        "- Read the raw code/prompt to ensure it matches our safety standards.",
        "",
        "## 3. Adapt",
        "Most external skills need adaptation to the Gemini Native Standard:",
        "1.  **Context**: Does it assume specific file paths?",
        "2.  **Format**: Convert to standard Markdown skill format.",
        '3.  **Refine**: Remove specific mentions of other agents (e.g., "You are Claude").',
        "",
        "## 4. Install",
        "Use the manager to fetch the raw file, then edit:",
        "```bash",
        'make skill-add source="owner/repo/path/to/skill.md"',
        "# Then edit the file in .agent/skills/",
        "```",
    ]
    return "\n".join(lines)


def get_list_skills_script() -> str:
    """Generate cross-platform list-skills script."""
    return '''#!/usr/bin/env python3
"""List available skills and workflows (cross-platform)."""
from pathlib import Path

def list_items(directory: str, label: str, emoji: str):
    """List markdown files in a directory."""
    path = Path(directory)
    if not path.exists():
        return

    items = sorted([f.stem for f in path.glob("*.md")])
    if items:
        print(f"\\n{emoji} {label}:")
        for item in items:
            print(f"   - {item}")

if __name__ == "__main__":
    list_items(".agent/skills", "Available Skills", "📚")
    list_items(".agent/workflows", "Available Workflows", "📋")
    list_items(".agent/patterns", "Available Patterns", "🎨")
    print()
'''
