#!/usr/bin/env python3
from pathlib import Path


def generate_index():
    docs_path = Path("docs")
    if not docs_path.exists():
        print("❌ docs/ directory not found.")
        return

    readme_content = [
        "# Workspace Index",
        "This file is automatically generated by `make index`. Do not edit manually.",
        "",
        "## 📁 Directories",
        "",
    ]

    # Define directory descriptions
    descriptions = {
        "standards": "Workspace rules and bootstrap protocols.",
        "projects": "Project-specific deep-dives and documentation.",
        "knowledge": "General research, notes, and shared learning.",
        "decisions": "Architecture Decision Records (ADRs).",
        "archive": "Historical context and deprecated documents.",
        "templates": "Standard document templates.",
    }

    folders = sorted([d for d in docs_path.iterdir() if d.is_dir()])

    for folder in folders:
        desc = descriptions.get(folder.name, "")
        header = f"### [{folder.name}](docs/{folder.name}/)"
        if desc:
            header += f" - {desc}"
        readme_content.append(header)

        # List files in folder (top level only)
        files = sorted(
            [f for f in folder.iterdir() if f.is_file() and not f.name.startswith(".")]
        )
        if files:
            for file in files:
                readme_content.append(
                    f"* [{file.name}](docs/{folder.name}/{file.name})"
                )
        else:
            readme_content.append("* (No documents yet)")
        readme_content.append("")

    readme_content.append("## 📝 Latest Changes")
    readme_content.append(
        "Check [docs/roadmap.md](docs/roadmap.md) for the latest project logs."
    )

    with open("README.md", "w") as f:
        f.write("\n".join(readme_content))

    print("✅ README.md updated with latest index.")


if __name__ == "__main__":
    generate_index()
